#!/usr/bin/env expect

set timeout -1
set secret [ exec cat secret.txt ]
#puts $secret
set password [ exec cat password.txt ]
#puts $password
set uid wangyaoshen
set host 10.225.5.31
puts "try to ssh $uid@$host"
spawn ssh $uid@$host
expect "Password:"
send "$password\n"
expect "Verification code:"
set vcode [ exec two-factor-auth -secret $secret -remainLimit 2 ]
set code [ exec echo $vcode | cut -d " " -f 1 ]
puts $vcode
send "$code\n"
interact
